[package]
name = "usbpd-traits"
description = "USB-PD library traits."
documentation = "https://docs.rs/usbpd-traits"
readme = "README.md"
keywords = ["no_std", "usb-pd", "embedded", "traits"]
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
defmt = { workspace = true, optional = true }

[features]
default = []
defmt = ["dep:defmt"]
