on:
  push:
  workflow_dispatch:

name: CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy --all-targets

      - name: Run clippy with defmt
        run: cargo clippy --all-targets --features defmt

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: cargo build --verbose

      - name: Run build with defmt
        run: cargo build --verbose --features defmt

      - name: Run tests
        run: cargo test --verbose

  docs:
    name: Docs

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      packages: read

    needs:
      - build_and_test

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv7m-none-eabi

      - name: Cache artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc

      # https://github.com/actions/upload-pages-artifact#file-permissions
      - run: chmod -c -R +rX ./target/thumbv7m-none-eabi/doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/thumbv7m-none-eabi/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
