on:
  push:
  workflow_dispatch:

name: CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy --all-targets

      - name: Run clippy with defmt
        run: cargo clippy --all-targets --features defmt

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: cargo build --verbose

      - name: Run build with defmt
        run: cargo build --verbose --features defmt

      - name: Run tests
        run: cargo test --verbose
