on:
  push:
  workflow_dispatch:

name: CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            examples/embassy-nucleo-h563zi
            examples/embassy-stm32-g431cb

      - name: Build
        run: bash .github/ci/build.sh

      - name: Test
        run: bash .github/ci/test.sh
