on:
  pull_request:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: rustup toolchain install nightly -c rustfmt

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            usbpd
            examples/embassy-nucleo-h563zi
            examples/embassy-nucleo-g474re-sink
            examples/embassy-nucleo-g474re-sink-epr
            examples/embassy-nucleo-g474re-source

      - name: Build
        run: bash .github/ci/build.sh

      - name: Test
        run: bash .github/ci/test.sh

      - name: Upload sink firmware
        uses: actions/upload-artifact@v4
        with:
          name: sink-firmware
          path: examples/embassy-nucleo-g474re-sink/target/thumbv7em-none-eabihf/release/usbpd-g474re-sink

      - name: Upload source firmware
        uses: actions/upload-artifact@v4
        with:
          name: source-firmware
          path: examples/embassy-nucleo-g474re-source/target/thumbv7em-none-eabihf/release/usbpd-g474re-source

  hardware_test:
    needs: build_and_test
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sink firmware
        uses: actions/download-artifact@v4
        with:
          name: sink-firmware

      - name: Download source firmware
        uses: actions/download-artifact@v4
        with:
          name: source-firmware

      - name: Hardware test
        env:
          PROBE_SERIAL_A: ${{ secrets.PROBE_SERIAL_A }}
          PROBE_SERIAL_B: ${{ secrets.PROBE_SERIAL_B }}
        run: bash .github/ci/hardware_test.sh
