on:
  push:
  workflow_dispatch:

name: CI

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy

      - name: Run clippy with defmt
        run: cargo clippy --features defmt

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: cargo build

      - name: Run build with defmt
        run: cargo build --features defmt

      - name: Run tests
        run: cargo test

  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: cargo build --manifest-path examples/embassy-stm32-g431cb/Cargo.toml
      - name: Run build
        run: cargo build --manifest-path examples/embassy-nucleo-h563zi/Cargo.toml
