on:
  push:
  pull_request:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
    
      - run: rustup toolchain install nightly -c rustfmt

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            usbpd
            examples/embassy-nucleo-h563zi
            examples/embassy-stm32-g431cb

      - name: Build
        run: bash .github/ci/build.sh

      - name: Test
        run: bash .github/ci/test.sh
